version: 2.1

orbs:
  node: circleci/node@4.4.0

jobs:
  lint-and-test:
    docker:
      - image: 'cimg/base:stable'
    executor:
      name: node/default
    steps:
      - checkout
      - node/install:
          node-version: 14.15.1
          npm-version: 7.12.0
      - node/install-packages
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Test
          command: npm run test

  build:
    docker:
      - image: 'cimg/base:stable'
    executor:
      name: node/default
    steps:
      - checkout
      - node/install:
          node-version: 14.15.1
          npm-version: 7.12.0
      - node/install-packages
      - run:
          name: Build
          command: npm run build

workflows:
  run_ci:
    jobs:
      - lint-and-test:
      - build:
          requires:
            - lint-and-test
          filters:
            branches:
              only:
                - main
