version: 2.1

orbs:
  node: circleci/node@4.4.0

commands:
  setup-node:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - node/install
      - node/install-npm
  install-packages:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - node/install-packages

jobs:
  lint-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - setup-node
      - install-packages
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Test
          command: npm run test

  build:
    executor:
      name: node/default
    steps:
      - checkout
      - setup-node
      - install-packages
      - run:
          name: Build
          command: npm run build

workflows:
  run_ci:
    jobs:
      - lint-and-test
      - build:
          requires:
            - lint-and-test
